name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Create STL models
  model:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: install nix
      uses: cachix/install-nix-action@v16
    - name: setup cachix
      uses: cachix/cachix-action@v8
      with:
        # Name of a cachix cache to push and pull/substitute
        name: marcus7070
        skipPush: true
    - name: build
      run: |
        nix shell -L github:marcus7070/cq-flake/8aafaa35aba1a2687a27960babbb2c59a1efd196#cadquery-env
        python ./box.py
    - name: Upload STLs
      uses: actions/upload-artifact@v3
      with:
        name: STLs
        path: ./*.stl
        
  # Build website job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Download STLs
        uses: actions/download-artifact@v3
        with:
          name: STLs
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
